#Idea from 3Blue1Brown --> https://www.youtube.com/watch?v=gB9n2gHsHN4 at 7:16
#Made it follow pattern except skip in between (depth1 = vid1, depth2 = vid3, depth3 = vid5)
from turtle import *
depth = int(raw_input("Pick a fractal depth (1-4--> above 4 takes a long time): "))
travel = float(raw_input("Size (read code for reccomendations): "))
def crazyFractal(travel, depth, angle):
    if depth > 0:
        hideturtle()
        color("red")
        crazyFractal(travel, depth-1, angle)
        forward(travel)
        left(angle)
        color("blue")
        crazyFractal(travel, depth-1, -angle)
        forward(travel)
        left(angle)
        color("red")
        crazyFractal(travel, depth-1, angle)
        forward(travel)
        right(angle)
        color("blue")
        crazyFractal(travel, depth-1, -angle)
        forward(travel)
        right(angle)
        color("red")
        crazyFractal(travel, depth-1, angle)
        forward(travel)
        right(angle)
        color("blue")
        crazyFractal(travel, depth-1, -angle)
        forward(travel)
        right(angle)
        color("red")
        crazyFractal(travel, depth-1, angle)
        forward(travel)
        left(angle)
        color("blue")
        crazyFractal(travel, depth-1, -angle)
        forward(travel)
        left(angle)
        color("red")
        crazyFractal(travel, depth-1, angle)
        forward(travel)
    else:
        forward(travel) #base case
speed(0)
pensize(1)
#travel is how long the turtle goes (length)
#travel parameter recommendations: depth = 0 (30-100), depth = 1 (10-50)
# depth = 2 (5-11), depth = 3 (1-3), depth = 4 (0.5) *note depth 4 takes like 30 min to draw 
#any depth above 4 is not reccomended but the fractal still works just takes a VERY LONG TIME to draw
#depth is the fractal depth (ie 0 is the base case, 1 is the second iteration)

crazyFractal(travel,depth,60) #angle is always 60 (30 and 45 make different fractals)
mainloop()
